{"data":[
{
"currentTime": "2020-11-09T16:56:58",
"endTime": "2023-11-15T00:00:00",
"id": 29408,
"product": {
"depict": "VIP套餐",
"id": 8,
"name": "VIP套餐",
"producttocontents": [
{
"id": 7,
"type": 1
}
]
},
"startTime": "2020-11-05T00:00:00",
"state": 1
}
],,"result":1,"total":0}